name: sen1511
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pyomo=6.4.1
    - pandas=1.4.3
    - matplotlib=3.5.3
    - jupyter
    - glpk=5.0
    - ipopt=3.14.9
    - pip
    - pip:
        - -e git+https://github.com/sjpfenninger/sen1511.git#egg=sen1511utils&subdirectory=sen1511utils
